/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.locadora.gui;

import br.ufmt.ic.locadora.exception.RegistroException;
import br.ufmt.ic.locadora.entidade.Funcionario;
import br.ufmt.ic.locadora.entidade.PessoaJuridica;
import br.ufmt.ic.locadora.dao.map.FabricaDAO;
import br.ufmt.ic.locadora.dao.DoacaoFilmesDAO;
import javax.swing.JOptionPane;
import br.ufmt.ic.locadora.entidade.DoacaoFilmes;

/**
 *
 * @author brunosette
 */
public class DoacaoJPanel extends javax.swing.JPanel {

    DoacaoFilmesDAO dao =FabricaDAO.CriarDoacaoFilmesDAO();
    /**
     * Creates new form DoacaoJPanel
     */
    public DoacaoJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filmejTextField = new javax.swing.JTextField();
        nomejLabel = new javax.swing.JLabel();
        telefonejLabel = new javax.swing.JLabel();
        entidadejTextField = new javax.swing.JTextField();
        emailjLabel = new javax.swing.JLabel();
        funcionariojTextField = new javax.swing.JTextField();
        limparjButton = new javax.swing.JButton();
        cadastrarjButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bancojTable = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createTitledBorder(null, "Doações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18)))); // NOI18N

        nomejLabel.setText("Filme:");

        telefonejLabel.setText("Entidade:");

        emailjLabel.setText("Funcionario:");

        limparjButton.setText("Limpar");
        limparjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparjButtonActionPerformed(evt);
            }
        });

        cadastrarjButton.setText("Cadastrar");
        cadastrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarjButtonActionPerformed(evt);
            }
        });

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        bancojTable.setModel(tableModel);
        jScrollPane1.setViewportView(bancojTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(limparjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrarjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telefonejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filmejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(funcionariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(editarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomejLabel)
                            .addComponent(filmejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarjButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonejLabel)
                            .addComponent(entidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailjLabel)
                            .addComponent(funcionariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadastrarjButton)
                            .addComponent(limparjButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limparjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButtonActionPerformed
        // TODO add your handling code here:
        filmejTextField.setText("");
        entidadejTextField.setText("");
        funcionariojTextField.setText("");

    }//GEN-LAST:event_limparjButtonActionPerformed

    private void cadastrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarjButtonActionPerformed
        // TODO add your handling code here:
        Funcionario func = new Funcionario();
        func.setNome(funcionariojTextField.getText());
        DoacaoFilmes doacao = new DoacaoFilmes(func);
        PessoaJuridica entidade = new PessoaJuridica();
        entidade.setNome(entidadejTextField.getText());
        doacao.setEntidade(entidade);
        
        
        try{
            dao.inserir(doacao);
            JOptionPane.showMessageDialog(this, "Cadastrado!");
            limparjButtonActionPerformed(null);
        }catch (RegistroException erro){
            JOptionPane.showMessageDialog(this, erro.getMessage());
            entidadejTextField.grabFocus();
        }
        
        
    }//GEN-LAST:event_cadastrarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:

        if (bancojTable.getSelectedRowCount() == 1) {
            linhaSelecionada = bancojTable.getSelectedRow();
            Banco selecionado = tableModel.getBanco(linhaSelecionada);

            nomejTextField.setText(selecionado.getNome());
            telefonejFormattedTextField.setText(selecionado.getTelefone());
            cepjFormattedTextField.setText(selecionado.getEndereco().getCep());
            ruajTextField.setText(selecionado.getEndereco().getRua());
            bairrojTextField.setText(selecionado.getEndereco().getBairro());
            estadojTextField.setText(selecionado.getEndereco().getEstado());
            cidadejTextField.setText(selecionado.getEndereco().getCidade());
            numerojTextField.setText(selecionado.getEndereco().getNumero());
            complementojTextField.setText(selecionado.getEndereco().getComplemento());
            editar = true;
        }else{
            JOptionPane.showMessageDialog(this, "Selecione somente 1 linha!");
        }
    }//GEN-LAST:event_editarjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bancojTable;
    private javax.swing.JButton cadastrarjButton;
    private javax.swing.JButton editarjButton;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JTextField entidadejTextField;
    private javax.swing.JTextField filmejTextField;
    private javax.swing.JTextField funcionariojTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparjButton;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JLabel telefonejLabel;
    // End of variables declaration//GEN-END:variables
}
