/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.locadora.gui;

import br.ufmt.ic.locadora.dao.FilmesDAO;
import br.ufmt.ic.locadora.exception.RegistroException;
import br.ufmt.ic.locadora.entidade.Funcionario;
import br.ufmt.ic.locadora.entidade.PessoaJuridica;
import br.ufmt.ic.locadora.entidade.Filme;
import locadora.FabricaDAO;
import br.ufmt.ic.locadora.tablemodel.EntradaFilmesTableModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author brunosette
 */
public class EntradaFilmesJPanel extends javax.swing.JPanel {

    FilmesDAO dao = FabricaDAO.CriarFilmesDAO();
    private EntradaFilmesTableModel tableModel;
    private boolean editar = false;
    private int linhaSelecionada;

    /**
     * Creates new form EstoqueFilmesJPanel
     */
    public EntradaFilmesJPanel() {
        tableModel = new EntradaFilmesTableModel(dao.listar());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomejLabel = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        telefonejLabel = new javax.swing.JLabel();
        fornecedorjTextField = new javax.swing.JTextField();
        funcionariojLabel = new javax.swing.JLabel();
        funcionarioJTextField = new javax.swing.JTextField();
        emailjLabel = new javax.swing.JLabel();
        limparjButton = new javax.swing.JButton();
        cadastrarjButton = new javax.swing.JButton();
        generoJTextField = new javax.swing.JTextField();
        funcionariojLabel1 = new javax.swing.JLabel();
        datajFormattedTextField = new javax.swing.JFormattedTextField();
        funcionariojLabel2 = new javax.swing.JLabel();
        quantidadejFormattedTextField = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        entradafilmesjTable = new javax.swing.JTable();
        editarjButton = new javax.swing.JButton();
        editarjButton1 = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createTitledBorder(null, "Entrada de Filmes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18)))); // NOI18N

        nomejLabel.setText("Nome:");

        telefonejLabel.setText("Fornecedor:");

        funcionariojLabel.setText("Funcionario:");

        emailjLabel.setText("Data:");

        limparjButton.setText("Limpar");
        limparjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparjButtonActionPerformed(evt);
            }
        });

        cadastrarjButton.setText("Salvar");
        cadastrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarjButtonActionPerformed(evt);
            }
        });

        funcionariojLabel1.setText("Genero:");

        try {
            datajFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        funcionariojLabel2.setText("Quantidade:");

        quantidadejFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        entradafilmesjTable.setModel(tableModel);
        jScrollPane1.setViewportView(entradafilmesjTable);

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        editarjButton1.setText("Editar");
        editarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButton1ActionPerformed(evt);
            }
        });

        excluirjButton.setText("Excluir");
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telefonejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(funcionariojLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(funcionarioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(funcionariojLabel1)
                                    .addComponent(emailjLabel)
                                    .addComponent(funcionariojLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(datajFormattedTextField)
                                    .addComponent(generoJTextField)
                                    .addComponent(quantidadejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editarjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(excluirjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(limparjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarjButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(339, 339, 339)
                    .addComponent(editarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(430, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nomejLabel)
                                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(editarjButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonejLabel)
                            .addComponent(fornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(excluirjButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(funcionariojLabel)
                            .addComponent(funcionarioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(funcionariojLabel1))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjLabel)
                            .addComponent(datajFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(funcionariojLabel2)
                            .addComponent(quantidadejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limparjButton)
                            .addComponent(cadastrarjButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(editarjButton)
                    .addContainerGap(157, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limparjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButtonActionPerformed
        // TODO add your handling code here:
        nomejTextField.setText("");
        datajFormattedTextField.setText("");
        funcionarioJTextField.setText("");
        datajFormattedTextField.setText("");
        generoJTextField.setText("");
        fornecedorjTextField.setText("");
        generoJTextField.setText("");
        quantidadejFormattedTextField.setText("");
        editar = false;
    }//GEN-LAST:event_limparjButtonActionPerformed

    private void cadastrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarjButtonActionPerformed
        // TODO add your handling code here:
        Filme estoque = new Filme();
        estoque.setGenero(generoJTextField.getText());
        estoque.setNomeFilme(nomejTextField.getText());
        Funcionario func = new Funcionario();
        func.setNome(funcionarioJTextField.getText());
        estoque.setFuncionario(func);
        PessoaJuridica fornecedor = new PessoaJuridica();
        fornecedor.setNome(fornecedorjTextField.getText());
        estoque.setFornecedor(fornecedor);
        Integer quant;

        try {
            quant = Integer.parseInt(quantidadejFormattedTextField.getText());
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(this, "Quantidade inválida");
            quantidadejFormattedTextField.grabFocus();
            return;
        }

        estoque.setQuantidade(quant);
        String sData = (String) datajFormattedTextField.getText();

        if (sData != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                estoque.setDatalancamento(sdf.parse(sData));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Data Inválida!");
                datajFormattedTextField.grabFocus();
                return;
            }
        }

        try {
            dao.inserir(estoque);
            JOptionPane.showMessageDialog(this, "Cadastrado!");
            limparjButtonActionPerformed(null);
            tableModel.adicionar(estoque);
        } catch (RegistroException erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
            nomejTextField.grabFocus();
        }


    }//GEN-LAST:event_cadastrarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:

        if (entradafilmesjTable.getSelectedRowCount() == 1) {
            linhaSelecionada = entradafilmesjTable.getSelectedRow();
            Filme selecionado = tableModel.getEntradaFilmes(linhaSelecionada);

            nomejTextField.setText(selecionado.getNomeFilme());
            fornecedorjTextField.setText(selecionado.getFornecedor().getNome());
            funcionarioJTextField.setText(selecionado.getFuncionario().getNome());
            generoJTextField.setText(selecionado.getGenero());
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                datajFormattedTextField.setText(sdf.format(selecionado.getDatalancamento()));
            } catch (NullPointerException erro) {

            }

            quantidadejFormattedTextField.setText(String.valueOf(selecionado.getQuantidade()));

            editar = true;
        } else {
            JOptionPane.showMessageDialog(this, "Selecione somente 1 linha!");
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void editarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarjButton1ActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:

        if (entradafilmesjTable.getSelectedRowCount() > 0) {
            int confirmacao = JOptionPane.showConfirmDialog(entradafilmesjTable, "Confirma a exclusão?");
            if (confirmacao == JOptionPane.YES_OPTION) {
                linhaSelecionada = entradafilmesjTable.getSelectedRow();
                Filme selecionado = tableModel.getEntradaFilmes(linhaSelecionada);
                dao.remover(selecionado.getNomeFilme());
                tableModel.remover(linhaSelecionada, selecionado);
                JOptionPane.showMessageDialog(this, "Excluido com Sucesso!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione ao menos 1 linha!");
        }
    }//GEN-LAST:event_excluirjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarjButton;
    private javax.swing.JFormattedTextField datajFormattedTextField;
    private javax.swing.JButton editarjButton;
    private javax.swing.JButton editarjButton1;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JTable entradafilmesjTable;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JTextField fornecedorjTextField;
    private javax.swing.JTextField funcionarioJTextField;
    private javax.swing.JLabel funcionariojLabel;
    private javax.swing.JLabel funcionariojLabel1;
    private javax.swing.JLabel funcionariojLabel2;
    private javax.swing.JTextField generoJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparjButton;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JFormattedTextField quantidadejFormattedTextField;
    private javax.swing.JLabel telefonejLabel;
    // End of variables declaration//GEN-END:variables
}
