/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.locadora.gui;

import br.ufmt.ic.locadora.dao.ExemplarDAO;
import br.ufmt.ic.locadora.exception.RegistroException;
import br.ufmt.ic.locadora.entidade.Funcionario;
import br.ufmt.ic.locadora.entidade.Filme;
import br.ufmt.ic.locadora.util.FabricaDAO;
import br.ufmt.ic.locadora.util.FabricaTela;
import br.ufmt.ic.locadora.tablemodel.EntradaFilmesTableModel;
import javax.swing.JOptionPane;
import br.ufmt.ic.locadora.dao.FilmeDAO;
import br.ufmt.ic.locadora.entidade.Fornecedor;
import br.ufmt.ic.locadora.entidade.Exemplar;

/**
 *
 * @author brunosette
 */
public class EntradaFilmesJPanel extends FabricaTela {

    FilmeDAO dao = FabricaDAO.CriarFilmeDAO();
    private EntradaFilmesTableModel tableModel;
    private boolean editar = false;
    private int linhaSelecionada;

    /**
     * Creates new form EstoqueFilmesJPanel
     */
    public EntradaFilmesJPanel() {
        tableModel = new EntradaFilmesTableModel(dao.listar());
        initComponents();
        funcionariojComboBox = super.setComboFuncionario(funcionariojComboBox);
        fornecedorjComboBox = super.setComboFornecedor(fornecedorjComboBox);
        exemplarjComboBox = super.setComboExemplar(exemplarjComboBox);
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomejLabel = new javax.swing.JLabel();
        telefonejLabel = new javax.swing.JLabel();
        funcionariojLabel = new javax.swing.JLabel();
        emailjLabel = new javax.swing.JLabel();
        limparjButton = new javax.swing.JButton();
        cadastrarjButton = new javax.swing.JButton();
        datajFormattedTextField = new javax.swing.JFormattedTextField();
        funcionariojLabel2 = new javax.swing.JLabel();
        quantidadejFormattedTextField = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        entradafilmesjTable = new javax.swing.JTable();
        editarjButton = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        exemplarjComboBox = new javax.swing.JComboBox();
        funcionariojComboBox = new javax.swing.JComboBox();
        fornecedorjComboBox = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createTitledBorder(null, "Entrada de Filmes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18)))); // NOI18N

        nomejLabel.setText("Exemplar:");

        telefonejLabel.setText("Fornecedor:");

        funcionariojLabel.setText("Funcionario:");

        emailjLabel.setText("Data:");

        limparjButton.setText("Limpar");
        limparjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparjButtonActionPerformed(evt);
            }
        });

        cadastrarjButton.setText("Salvar");
        cadastrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarjButtonActionPerformed(evt);
            }
        });

        try {
            datajFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        funcionariojLabel2.setText("Quantidade:");

        quantidadejFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        entradafilmesjTable.setModel(tableModel);
        jScrollPane1.setViewportView(entradafilmesjTable);

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        excluirjButton.setText("Excluir");
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });

        exemplarjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        funcionariojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        funcionariojComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariojComboBoxActionPerformed(evt);
            }
        });

        fornecedorjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fornecedorjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorjComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emailjLabel)
                                    .addComponent(funcionariojLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(datajFormattedTextField)
                                    .addComponent(quantidadejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomejLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(funcionariojLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(telefonejLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(exemplarjComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 115, Short.MAX_VALUE)
                                    .addComponent(funcionariojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fornecedorjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(excluirjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(limparjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrarjButton)
                        .addGap(108, 108, 108)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(excluirjButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exemplarjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomejLabel)
                            .addComponent(editarjButton))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonejLabel)
                            .addComponent(fornecedorjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcionariojLabel)
                    .addComponent(funcionariojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailjLabel)
                    .addComponent(datajFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcionariojLabel2)
                    .addComponent(quantidadejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparjButton)
                    .addComponent(cadastrarjButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limparjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButtonActionPerformed
        // TODO add your handling code here:
        exemplarjComboBox.setSelectedIndex(0);
        funcionariojComboBox.setSelectedIndex(0);
        fornecedorjComboBox.setSelectedIndex(0);
        
        datajFormattedTextField.setText("");
        datajFormattedTextField.setText("");
        
        quantidadejFormattedTextField.setText("");
        editar = false;
    }//GEN-LAST:event_limparjButtonActionPerformed

    private void cadastrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarjButtonActionPerformed
        // TODO add your handling code here:
        Filme novo = new Filme();
        
        
        if (ValidaCombo(fornecedorjComboBox)){
            novo.setFornecedor((Fornecedor) fornecedorjComboBox.getSelectedItem());
        }else{
            fornecedorjComboBox.grabFocus();
            return;
        }
        
        if (ValidaCombo(funcionariojComboBox)){
            novo.setFuncionario((Funcionario) funcionariojComboBox.getSelectedItem());
        }else{
            funcionariojComboBox.grabFocus();
            return;
        }
        
        if (ValidaCombo(exemplarjComboBox)){
            novo.setExemplar((Exemplar) exemplarjComboBox.getSelectedItem());
        }else{
            exemplarjComboBox.grabFocus();
            return;
        }
        
        Integer quant;

        try {
            quant = Integer.parseInt(quantidadejFormattedTextField.getText());
            if (quant == 0){
                throw new NumberFormatException();
            }
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(this, "Quantidade inválida");
            quantidadejFormattedTextField.grabFocus();
            return;
        }

        novo.setQuantidade(quant);
        

        try {
            dao.inserir(novo);
            JOptionPane.showMessageDialog(this, "Cadastrado!");
            limparjButtonActionPerformed(null);
            tableModel.adicionar(novo);
        } catch (RegistroException erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
            exemplarjComboBox.grabFocus();
        }


    }//GEN-LAST:event_cadastrarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:

        if (entradafilmesjTable.getSelectedRowCount() == 1) {
            linhaSelecionada = entradafilmesjTable.getSelectedRow();
            Filme selecionado = tableModel.getEntradaFilmes(linhaSelecionada);
            
            exemplarjComboBox.setSelectedItem(selecionado.getExemplar());
            fornecedorjComboBox.setSelectedItem(selecionado.getFornecedor());
            funcionariojComboBox.setSelectedItem(selecionado.getFuncionario());
            
            quantidadejFormattedTextField.setText(String.valueOf(selecionado.getQuantidade()));

            editar = true;
        } else {
            JOptionPane.showMessageDialog(this, "Selecione somente 1 linha!");
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:

        if (entradafilmesjTable.getSelectedRowCount() > 0) {
            int confirmacao = JOptionPane.showConfirmDialog(entradafilmesjTable, "Confirma a exclusão?");
            if (confirmacao == JOptionPane.YES_OPTION) {
                linhaSelecionada = entradafilmesjTable.getSelectedRow();
                Filme selecionado = tableModel.getEntradaFilmes(linhaSelecionada);
                dao.remover(selecionado);
                tableModel.remover(linhaSelecionada, selecionado);
                JOptionPane.showMessageDialog(this, "Excluido com Sucesso!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione ao menos 1 linha!");
        }
    }//GEN-LAST:event_excluirjButtonActionPerformed

    private void funcionariojComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariojComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcionariojComboBoxActionPerformed

    private void fornecedorjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorjComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarjButton;
    private javax.swing.JFormattedTextField datajFormattedTextField;
    private javax.swing.JButton editarjButton;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JTable entradafilmesjTable;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JComboBox exemplarjComboBox;
    private javax.swing.JComboBox fornecedorjComboBox;
    private javax.swing.JComboBox funcionariojComboBox;
    private javax.swing.JLabel funcionariojLabel;
    private javax.swing.JLabel funcionariojLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparjButton;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JFormattedTextField quantidadejFormattedTextField;
    private javax.swing.JLabel telefonejLabel;
    // End of variables declaration//GEN-END:variables
}
