/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufmt.ic.locadora.gui;

import br.ufmt.ic.locadora.exception.RegistroException;
import br.ufmt.ic.locadora.entidade.Funcionario;
import br.ufmt.ic.locadora.entidade.ReservaFilme;
import br.ufmt.ic.locadora.entidade.Cliente;
import br.ufmt.ic.locadora.entidade.Filme;
import br.ufmt.ic.locadora.util.FabricaDAO;
import br.ufmt.ic.locadora.dao.ReservaFilmeDAO;
import br.ufmt.ic.locadora.entidade.Genero;
import br.ufmt.ic.locadora.tablemodel.ReservaFilmeTableModel;
import br.ufmt.ic.locadora.util.FabricaTela;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class ReservafilmeJPanel extends FabricaTela {

    ReservaFilmeDAO dao = FabricaDAO.CriarReservaFilmeDAO();
    private ReservaFilmeTableModel tableModel;
    private boolean editar = false;
    private int linhaSelecionada;
    private ReservaFilme chave;

    /**
     * Creates new form reservafilmeJPanel
     */
    public ReservafilmeJPanel() {
        tableModel = new ReservaFilmeTableModel(dao.listar());

        initComponents();
        LimpaComboFilme();
        funcionariojComboBox = super.setComboFuncionario(funcionariojComboBox);
        generojComboBox = super.setComboGenero(generojComboBox);
        clientejComboBox = super.setComboCliente(clientejComboBox);

    }

    private void LimpaComboFilme() {
        filmejComboBox.removeAllItems();
        filmejComboBox.addItem("Esperando ...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        limparjButton = new javax.swing.JButton();
        cadastrarjButton = new javax.swing.JButton();
        nomejLabel = new javax.swing.JLabel();
        telefonejLabel = new javax.swing.JLabel();
        funcionariojLabel = new javax.swing.JLabel();
        emailjLabel = new javax.swing.JLabel();
        datadevolucaojFormattedTextField = new javax.swing.JFormattedTextField();
        emailjLabel1 = new javax.swing.JLabel();
        dataemprestimojFormattedTextField = new javax.swing.JFormattedTextField();
        editarjButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservaFilmejTable = new javax.swing.JTable();
        excluirjButton = new javax.swing.JButton();
        generojComboBox = new javax.swing.JComboBox();
        nomejLabel1 = new javax.swing.JLabel();
        filmejComboBox = new javax.swing.JComboBox();
        funcionariojComboBox = new javax.swing.JComboBox();
        clientejComboBox = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createTitledBorder(null, "Reservar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18)))); // NOI18N

        limparjButton.setText("Limpar");
        limparjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparjButtonActionPerformed(evt);
            }
        });

        cadastrarjButton.setText("Cadastrar");
        cadastrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarjButtonActionPerformed(evt);
            }
        });

        nomejLabel.setText("Cliente:");

        telefonejLabel.setText("Filme:");

        funcionariojLabel.setText("Funcionario:");

        emailjLabel.setText("Data devolução:");

        try {
            datadevolucaojFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        emailjLabel1.setText("Data empréstimo:");

        try {
            dataemprestimojFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        editarjButton1.setText("Editar");
        editarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButton1ActionPerformed(evt);
            }
        });

        reservaFilmejTable.setModel(tableModel);
        jScrollPane1.setViewportView(reservaFilmejTable);

        excluirjButton.setText("Excluir");
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });

        generojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        generojComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                generojComboBoxItemStateChanged(evt);
            }
        });

        nomejLabel1.setText("Genero:");

        filmejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        funcionariojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        clientejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(nomejLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clientejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(nomejLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(generojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editarjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(excluirjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(limparjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadastrarjButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(funcionariojLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emailjLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataemprestimojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(funcionariojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datadevolucaojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(telefonejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filmejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(emailjLabel1)
                        .addGap(219, 219, 219)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomejLabel)
                            .addComponent(editarjButton1)
                            .addComponent(clientejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(excluirjButton)
                            .addComponent(nomejLabel1)
                            .addComponent(generojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonejLabel)
                            .addComponent(filmejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(funcionariojLabel)
                            .addComponent(funcionariojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataemprestimojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailjLabel)
                            .addComponent(datadevolucaojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limparjButton)
                            .addComponent(cadastrarjButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limparjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButtonActionPerformed
        // TODO add your handling code here:

        datadevolucaojFormattedTextField.setText("");
        dataemprestimojFormattedTextField.setText("");

        clientejComboBox.setSelectedIndex(0);
        filmejComboBox.setSelectedIndex(0);
        funcionariojComboBox.setSelectedIndex(0);
        generojComboBox.setSelectedIndex(0);
        editar = false;
    }//GEN-LAST:event_limparjButtonActionPerformed

    private void cadastrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarjButtonActionPerformed
        // TODO add your handling code here:
        ReservaFilme reserva = new ReservaFilme();

        if (ValidaCombo(filmejComboBox)) {
            reserva.setFilme((Filme) filmejComboBox.getSelectedItem());
        } else {
            filmejComboBox.grabFocus();
            return;
        }

        if (ValidaCombo(clientejComboBox)) {
            reserva.setCliente((Cliente) clientejComboBox.getSelectedItem());
        } else {
            clientejComboBox.grabFocus();
            return;
        }

        if (ValidaCombo(funcionariojComboBox)) {
            reserva.setFuncionario((Funcionario) funcionariojComboBox.getSelectedItem());
        } else {
            funcionariojComboBox.grabFocus();
            return;
        }

        String sData = (String) datadevolucaojFormattedTextField.getText();

        if (sData != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                reserva.setDataDevolucao(sdf.parse(sData));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Data de devolução Inválida!");
                datadevolucaojFormattedTextField.grabFocus();
                return;
            }
        }

        sData = (String) dataemprestimojFormattedTextField.getText();

        if (sData != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                reserva.setDataReserva(sdf.parse(sData));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Data de emprestimo Inválida!");
                dataemprestimojFormattedTextField.grabFocus();
                return;
            }
        }

        try {
            if (editar) {
                dao.alterar(reserva);
                JOptionPane.showMessageDialog(this, "Alterado!");
                tableModel.alterar(linhaSelecionada, reserva);
            } else {
                dao.inserir(reserva);
                JOptionPane.showMessageDialog(this, "Cadastrado!");
                tableModel.adicionar(reserva);
            }
            limparjButtonActionPerformed(null);
        } catch (RegistroException erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
            filmejComboBox.grabFocus();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao inserir, verifique os dados");
            filmejComboBox.grabFocus();
            Logger.getLogger(ReservafilmeJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_cadastrarjButtonActionPerformed

    private void editarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButton1ActionPerformed
        // TODO add your handling code here:

        if (reservaFilmejTable.getSelectedRowCount() == 1) {
            linhaSelecionada = reservaFilmejTable.getSelectedRow();
            ReservaFilme selecionado = tableModel.getReservaFilme(linhaSelecionada);

            for (int i = 1; i < generojComboBox.getItemCount(); i++) {
                Genero genero = (Genero) generojComboBox.getItemAt(i);
                if (genero.getNome().equals(selecionado.getFilme().getExemplar().getGenero().getNome())) {
                    generojComboBox.setSelectedIndex(i);
                }
            }

            for (int i = 1; i < clientejComboBox.getItemCount(); i++) {
                Cliente fornecedor = (Cliente) clientejComboBox.getItemAt(i);
                if (fornecedor.getCpf().equals(selecionado.getCliente().getCpf())) {
                    clientejComboBox.setSelectedIndex(i);
                }
            }

            for (int i = 1; i < funcionariojComboBox.getItemCount(); i++) {
                Funcionario funcionario = (Funcionario) funcionariojComboBox.getItemAt(i);
                if (funcionario.getCpf().equals(selecionado.getFuncionario().getCpf())) {
                    funcionariojComboBox.setSelectedIndex(i);
                }
            }

            clientejComboBox.setSelectedItem((Cliente) selecionado.getCliente());
            //filmejComboBox.setSelectedItem((Filme) selecionado.getFilme());

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                dataemprestimojFormattedTextField.setText(sdf.format(selecionado.getDataReserva()));

            } catch (NullPointerException erro) {
            }
            try {
                datadevolucaojFormattedTextField.setText(sdf.format(selecionado.getDataDevolucao()));
            } catch (NullPointerException erro) {

            }
            chave = selecionado;
            editar = true;
        } else {
            JOptionPane.showMessageDialog(this, "Selecione somente 1 linha!");
        }
    }//GEN-LAST:event_editarjButton1ActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:

        if (reservaFilmejTable.getSelectedRowCount() > 0) {
            int confirmacao = JOptionPane.showConfirmDialog(reservaFilmejTable, "Confirma a exclusão?");
            if (confirmacao == JOptionPane.YES_OPTION) {
                linhaSelecionada = reservaFilmejTable.getSelectedRow();
                ReservaFilme selecionado = tableModel.getReservaFilme(linhaSelecionada);
                try {
                    dao.remover(selecionado.getCodigo());
                    tableModel.remover(linhaSelecionada, selecionado);
                    JOptionPane.showMessageDialog(this, "Excluido com Sucesso!");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Não foi possivel remover. Outros dados dependem deste");

                    Logger.getLogger(ReservafilmeJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione ao menos 1 linha!");
        }
    }//GEN-LAST:event_excluirjButtonActionPerformed

    private void generojComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_generojComboBoxItemStateChanged
        // TODO add your handling code here:
        if (generojComboBox.getSelectedIndex() > 0) {
            filmejComboBox = setComboFilme(filmejComboBox, (Genero) generojComboBox.getSelectedItem());
            if (filmejComboBox.getItemCount() < 2) {
                filmejComboBox.removeAllItems();
                filmejComboBox.addItem("Sem Dados ...");
            }
        } else {
            LimpaComboFilme();

        }
    }//GEN-LAST:event_generojComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarjButton;
    private javax.swing.JComboBox clientejComboBox;
    private javax.swing.JFormattedTextField datadevolucaojFormattedTextField;
    private javax.swing.JFormattedTextField dataemprestimojFormattedTextField;
    private javax.swing.JButton editarjButton1;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JLabel emailjLabel1;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JComboBox filmejComboBox;
    private javax.swing.JComboBox funcionariojComboBox;
    private javax.swing.JLabel funcionariojLabel;
    private javax.swing.JComboBox generojComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparjButton;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JLabel nomejLabel1;
    private javax.swing.JTable reservaFilmejTable;
    private javax.swing.JLabel telefonejLabel;
    // End of variables declaration//GEN-END:variables
}
